title: "AI Product Manager Portfolio"
description: "Showcasing my AI‑product ideas, micro‑apps and thoughts."
theme: jekyll-theme-cayman
# Correct Markdown processor (Jekyll’s default).
markdown: kramdown
permalink: /:year/:month/:day/:title/
# Values used in _layouts/default.html
github:
  username: SatyaDileep
linkedin: satya-dileep-kumar-thotakura-9b25021b/
